// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDV3N_aSJqwGugYLPmpkY2vvfB1PJckO0',
    appId: '1:72458102035:web:7d49d9007979885a10e6e6',
    messagingSenderId: '72458102035',
    projectId: 'lazca-sozluk-25a36',
    authDomain: 'lazca-sozluk-25a36.firebaseapp.com',
    storageBucket: 'lazca-sozluk-25a36.appspot.com',
    measurementId: 'G-C5T6GRB3DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhTGeuRUk4yyBhqdo9HOmeriXtX9lvQzs',
    appId: '1:72458102035:android:6bb292a154a28c1510e6e6',
    messagingSenderId: '72458102035',
    projectId: 'lazca-sozluk-25a36',
    storageBucket: 'lazca-sozluk-25a36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-nbZYBX1vSfYIDI8N-MvCzu682yWCk38',
    appId: '1:72458102035:ios:f4e8f32b11b3319d10e6e6',
    messagingSenderId: '72458102035',
    projectId: 'lazca-sozluk-25a36',
    storageBucket: 'lazca-sozluk-25a36.appspot.com',
    iosClientId: '72458102035-0cokcgbl5mgf6cm9qvfqokjo0r92971m.apps.googleusercontent.com',
    iosBundleId: 'com.example.lazcaSozluk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-nbZYBX1vSfYIDI8N-MvCzu682yWCk38',
    appId: '1:72458102035:ios:f4e8f32b11b3319d10e6e6',
    messagingSenderId: '72458102035',
    projectId: 'lazca-sozluk-25a36',
    storageBucket: 'lazca-sozluk-25a36.appspot.com',
    iosClientId: '72458102035-0cokcgbl5mgf6cm9qvfqokjo0r92971m.apps.googleusercontent.com',
    iosBundleId: 'com.example.lazcaSozluk',
  );
}
